remiii_aws_download_check_video:
    path:     /video/{videoNumber}
    defaults: { _controller: remiiiAWSDownloadCheckBundle:Default:video }
    requirements:
        videoNumber: "[1-1]"

remiii_aws_download_check_final:
    path:     /final
    defaults: { _controller: remiiiAWSDownloadCheckBundle:Default:final }

remiii_aws_download_check_admin:
    path:     /admin
    defaults: { _controller: remiiiAWSDownloadCheckBundle:Default:admin }

