remiii_aws_download_check:
    resource: "@remiiiAWSDownloadCheckBundle/Resources/config/routing.yml"
    prefix:   /

remiii_corporate:
    resource: "@remiiiCorporateBundle/Resources/config/routing.yml"
    prefix:   /

remiii_global:
    resource: "@remiiiGlobalBundle/Resources/config/routing.yml"
    prefix:   /

