remiii_aws_download_check:
    resource: "@remiiiAWSDownloadCheckBundle/Controller/"
    type:     annotation
    prefix:   /

remiii_corporate:
    resource: "@remiiiCorporateBundle/Controller/"
    type:     annotation
    prefix:   /

remiii_global:
    resource: "@remiiiGlobalBundle/Controller/"
    type:     annotation
    prefix:   /

